baseURL = "https://dilexnetworks.github.io/dilex-hugo-shortcodes/"
title = "Dilex Hugo Shortcodes"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]

[params]
  homeLink = "https://dilexnetworks.github.io/dilex-hugo-shortcodes/"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = true
    style = "github-dark"


[menus]
  [[menus.main]]
    name = "Getting Started"
    pageRef = "/getting-started"
    weight = 10

  [[menus.main]]
    name = "Shortcodes"
    pageRef = "/shortcodes"
    weight = 20

  [[menus.main]]
    name = "Guides"
    pageRef = "/guides"
    weight = 30