baseURL = "https://dilexnetworks.github.io/core-hugo-shortcodes/"
title = "Core Hugo Shortcodes"
disableKinds = ["taxonomy", "term", "RSS", "sitemap", "robotsTXT"]

[params]
  homeLink = "https://dilexnetworks.github.io/core-hugo-shortcodes/"
  repo = "https://github.com/DilexNetworks/core-hugo-shortcodes"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    noClasses = true
    style = "github-dark"

[module]
  [[module.imports]]
    path = "github.com/DilexNetworks/core-hugo-shortcodes/module"

[menus]
  [[menus.main]]
    name = "Getting Started"
    pageRef = "/getting-started"
    weight = 10

  [[menus.main]]
    name = "Shortcodes"
    pageRef = "/shortcodes"
    weight = 20

  [[menus.main]]
    name = "Guides"
    pageRef = "/guides"
    weight = 30
